"""Export elastic tensors in MOOSE-friendly tables and input snippets."""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any

import numpy as np

from atomi.elastic.viz import load_elastic_records, safe_label


VOIGT_FIELDS = [f"C{i}{j}_Pa" for i in range(1, 7) for j in range(i, 7)]


def write_json(path: Path, data: Any) -> None:
    def norm(value: Any) -> Any:
        if isinstance(value, Path):
            return str(value)
        if isinstance(value, np.ndarray):
            return value.tolist()
        if isinstance(value, np.generic):
            return value.item()
        if isinstance(value, dict):
            return {str(k): norm(v) for k, v in value.items()}
        if isinstance(value, (list, tuple)):
            return [norm(v) for v in value]
        return value

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(norm(data), indent=2, sort_keys=True) + "\n", encoding="utf-8")


def tensor_voigt_pa(tensor_gpa: np.ndarray) -> dict[str, float]:
    tensor_pa = np.asarray(tensor_gpa, dtype=float) * 1.0e9
    out: dict[str, float] = {}
    for i in range(6):
        for j in range(i, 6):
            out[f"C{i + 1}{j + 1}_Pa"] = float(tensor_pa[i, j])
    return out


def format_num(value: Any) -> str:
    if value is None:
        return ""
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if not math.isfinite(number):
        return ""
    return f"{number:.12g}"


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: format_num(row.get(field, "")) for field in fields})


def symmetric21_values(row: dict[str, Any]) -> list[float]:
    order = [
        "C11_Pa",
        "C12_Pa",
        "C13_Pa",
        "C14_Pa",
        "C15_Pa",
        "C16_Pa",
        "C22_Pa",
        "C23_Pa",
        "C24_Pa",
        "C25_Pa",
        "C26_Pa",
        "C33_Pa",
        "C34_Pa",
        "C35_Pa",
        "C36_Pa",
        "C44_Pa",
        "C45_Pa",
        "C46_Pa",
        "C55_Pa",
        "C56_Pa",
        "C66_Pa",
    ]
    return [float(row.get(field, 0.0) or 0.0) for field in order]


def write_moose_include(path: Path, rows: list[dict[str, Any]], *, material: str, temperature_variable: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# MOOSE elasticity include generated by Atomi.",
        "# Units: SI. Elastic constants are Pa.",
        "# The constant ComputeElasticityTensor blocks are ready to copy for a single temperature.",
        "# The PiecewiseLinear functions provide Cij(T) data for custom/function-based materials.",
        "",
        "[Functions]",
    ]
    temp_rows = [row for row in rows if row.get("T_K") not in (None, "")]
    if temp_rows:
        x_values = " ".join(format_num(row["T_K"]) for row in temp_rows)
        for field in VOIGT_FIELDS:
            if any(row.get(field) not in (None, "") for row in temp_rows):
                lines.extend(
                    [
                        f"  [./{field}]",
                        "    type = PiecewiseLinear",
                        f"    x = '{x_values}'",
                        f"    y = '{' '.join(format_num(row.get(field)) for row in temp_rows)}'",
                        "  [../]",
                    ]
                )
    lines.append("[]")
    lines.extend(["", "[Materials]"])
    for row in rows:
        label = safe_label(str(row.get("label") or f"T{row.get('T_K', len(lines))}"))
        temp = row.get("T_K")
        block = f"{material}_{label}_elasticity"
        lines.extend(
            [
                f"  [./{block}]",
                "    type = ComputeElasticityTensor",
                "    fill_method = symmetric21",
                f"    C_ijkl = '{' '.join(format_num(value) for value in symmetric21_values(row))}'",
                f"    # source_label = {row.get('source', '')}",
                f"    # temperature_K = {format_num(temp)}",
                "  [../]",
            ]
        )
    if temp_rows:
        lines.extend(
            [
                "",
                "  [./elastic_Cij_functions]",
                "    type = GenericFunctionMaterial",
                f"    prop_names = '{' '.join(VOIGT_FIELDS)}'",
                f"    prop_values = '{' '.join(VOIGT_FIELDS)}'",
                f"    # temperature variable expected by functions: {temperature_variable}",
                "    # Use this block as a data bridge for a custom temperature-dependent anisotropic tensor material.",
                "  [../]",
            ]
        )
    lines.append("[]")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="moose-elastic-export",
        description="Export VASP/MD elastic tensors as MOOSE-friendly SI tables and include snippets.",
    )
    parser.add_argument("--elastic-dir", type=Path, default=Path("."), help="Directory containing elastic_tensors.json.")
    parser.add_argument("--elastic-tensors", type=Path, help="Explicit elastic_tensors.json path.")
    parser.add_argument("--elastic-table", type=Path, help="Optional elastic_moduli_T.csv path.")
    parser.add_argument("--outdir", type=Path, default=Path("analysis/moose_elastic"))
    parser.add_argument("--material", default="material")
    parser.add_argument("--temperature-variable", default="T")
    return parser


def main(argv: list[str] | None = None) -> dict[str, Any]:
    args = build_parser().parse_args(argv)
    elastic_dir = args.elastic_dir.resolve()
    tensors = (args.elastic_tensors or (elastic_dir / "elastic_tensors.json")).resolve()
    table = (args.elastic_table or (elastic_dir / "elastic_moduli_T.csv")).resolve()
    records = load_elastic_records(tensors, table if table.exists() else None)
    rows: list[dict[str, Any]] = []
    tensors_json: list[dict[str, Any]] = []
    for record in records:
        row = {
            "label": record.label,
            "source": record.source,
            "T_K": record.temperature_K,
            **tensor_voigt_pa(record.tensor_GPa),
        }
        rows.append(row)
        tensors_json.append(
            {
                "label": record.label,
                "source": record.source,
                "temperature_K": record.temperature_K,
                "C_voigt_Pa": (np.asarray(record.tensor_GPa, dtype=float) * 1.0e9).tolist(),
            }
        )
    outdir = args.outdir.resolve()
    csv_path = outdir / "moose_elastic_tensors.csv"
    json_path = outdir / "moose_elastic_tensors.json"
    include_path = outdir / f"{safe_label(args.material)}_elasticity.i"
    write_csv(csv_path, rows, ["label", "source", "T_K", *VOIGT_FIELDS])
    write_json(
        json_path,
        {
            "schema": "atomi.moose.elastic_tensors.v1",
            "units": "SI",
            "source": str(tensors),
            "records": tensors_json,
        },
    )
    write_moose_include(include_path, rows, material=safe_label(args.material), temperature_variable=args.temperature_variable)
    metadata = {
        "outputs": {
            "csv": str(csv_path),
            "json": str(json_path),
            "moose_include": str(include_path),
        },
        "n_records": len(rows),
        "notes": [
            "Constant ComputeElasticityTensor blocks are directly reusable for fixed-temperature mechanics.",
            "PiecewiseLinear Cij(T) functions are provided as a bridge for custom/function-based anisotropic tensor materials.",
        ],
    }
    write_json(outdir / "moose_elastic_export_metadata.json", metadata)
    print(f"Wrote MOOSE elastic tensor CSV: {csv_path}")
    print(f"Wrote MOOSE include template: {include_path}")
    return metadata


if __name__ == "__main__":
    main()
