"""Bridge defect-motif energetics into zentropy/CALPHAD/MOOSE tables."""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from pathlib import Path
from typing import Any


EV_PER_DEFECT_TO_KJ_MOL = 96.48533212331002
AVOGADRO = 6.02214076e23
A3_TO_M3 = 1.0e-30


def finite_float(value: Any) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    return number if math.isfinite(number) else None


def safe_name(value: str) -> str:
    return re.sub(r"[^0-9A-Za-z_+-]+", "_", value.strip()).strip("_") or "defect"


def format_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if not math.isfinite(number):
        return ""
    return f"{number:.12g}"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: format_value(row.get(field)) for field in fields})


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def normalize_defect_rows(rows: list[dict[str, str]], *, temperature_K: float | None) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for idx, row in enumerate(rows, start=1):
        defect_id = row.get("defect_id") or row.get("motif_id") or row.get("name") or f"defect_{idx}"
        formation_e = finite_float(row.get("formation_energy_eV") or row.get("E_form_eV"))
        migration_e = finite_float(row.get("migration_barrier_eV") or row.get("E_migration_eV"))
        volume_a3 = finite_float(row.get("volume_change_A3") or row.get("defect_volume_A3"))
        prefactor = finite_float(row.get("prefactor_cm2_s") or row.get("D0_cm2_s"))
        clean: dict[str, Any] = {
            "defect_id": defect_id,
            "motif_family": row.get("motif_family") or "",
            "composition": row.get("composition") or "",
            "charge": finite_float(row.get("charge")),
            "valence_state": row.get("valence_state") or "",
            "magmom_label": row.get("magmom_label") or row.get("spin_label") or "",
            "site_fraction": finite_float(row.get("site_fraction")),
            "degeneracy": finite_float(row.get("degeneracy")) or 1.0,
            "formation_energy_eV": formation_e,
            "formation_energy_kJ_mol": formation_e * EV_PER_DEFECT_TO_KJ_MOL if formation_e is not None else None,
            "migration_barrier_eV": migration_e,
            "migration_barrier_kJ_mol": migration_e * EV_PER_DEFECT_TO_KJ_MOL if migration_e is not None else None,
            "volume_change_A3": volume_a3,
            "defect_volume_m3_mol": volume_a3 * A3_TO_M3 * AVOGADRO if volume_a3 is not None else None,
            "elastic_dipole_GPa_A3": finite_float(row.get("elastic_dipole_GPa_A3")),
            "eigenstrain_trace": finite_float(row.get("eigenstrain_trace")),
            "prefactor_cm2_s": prefactor,
            "D0_m2_s": prefactor * 1.0e-4 if prefactor is not None else None,
            "temperature_K": finite_float(row.get("temperature_K")) or temperature_K,
            "source": row.get("source") or "",
            "notes": row.get("notes") or "",
        }
        out.append(clean)
    return out


def write_moose_template(path: Path, rows: list[dict[str, Any]], *, material: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# MOOSE defect thermodynamics bridge generated by Atomi.",
        "# Use these values as inputs to app-specific defect chemistry, eigenstrain, or phase-field kernels.",
        "# Energies are per mole of defect species when using *_kJ_mol fields.",
        "",
        "[Materials]",
    ]
    for row in rows:
        name = safe_name(str(row["defect_id"]))
        lines.extend(
            [
                f"  [./{safe_name(material)}_{name}_defect_constants]",
                "    type = GenericConstantMaterial",
                "    prop_names = 'E_form_kJ_mol E_migration_kJ_mol defect_volume_m3_mol eigenstrain_trace D0_m2_s'",
                "    prop_values = '"
                + " ".join(
                    format_value(row.get(field))
                    for field in (
                        "formation_energy_kJ_mol",
                        "migration_barrier_kJ_mol",
                        "defect_volume_m3_mol",
                        "eigenstrain_trace",
                        "D0_m2_s",
                    )
                )
                + "'",
                "  [../]",
            ]
        )
    lines.extend(["[]", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="defect_thermo_export",
        description=(
            "Convert defect motif energetics into zentropy/CALPHAD species tables "
            "and MOOSE defect-property templates."
        ),
    )
    parser.add_argument("--defect-csv", type=Path, required=True, help="CSV of defect motif energetics.")
    parser.add_argument("--motif-db-json", type=Path, help="Optional zentropy motif DB JSON path recorded in metadata.")
    parser.add_argument("--outdir", type=Path, default=Path("analysis/defect_thermo"))
    parser.add_argument("--material", default="material")
    parser.add_argument("--temperature-K", type=float, help="Default temperature assigned when rows omit temperature.")
    return parser


def main(argv: list[str] | None = None) -> dict[str, Any]:
    args = build_parser().parse_args(argv)
    rows = normalize_defect_rows(read_csv(args.defect_csv.resolve()), temperature_K=args.temperature_K)
    outdir = args.outdir.resolve()
    fields = [
        "defect_id",
        "motif_family",
        "composition",
        "charge",
        "valence_state",
        "magmom_label",
        "site_fraction",
        "degeneracy",
        "formation_energy_eV",
        "formation_energy_kJ_mol",
        "migration_barrier_eV",
        "migration_barrier_kJ_mol",
        "volume_change_A3",
        "defect_volume_m3_mol",
        "elastic_dipole_GPa_A3",
        "eigenstrain_trace",
        "prefactor_cm2_s",
        "D0_m2_s",
        "temperature_K",
        "source",
        "notes",
    ]
    table = outdir / "defect_thermo_table.csv"
    species = outdir / "calphad_defect_species.csv"
    moose = outdir / f"{safe_name(args.material)}_defect_thermo.i"
    write_csv(table, rows, fields)
    write_csv(
        species,
        rows,
        [
            "defect_id",
            "composition",
            "charge",
            "formation_energy_kJ_mol",
            "degeneracy",
            "site_fraction",
            "magmom_label",
        ],
    )
    write_moose_template(moose, rows, material=args.material)
    metadata = {
        "schema": "atomi.zentropy.defect_thermo.v1",
        "inputs": {
            "defect_csv": str(args.defect_csv.resolve()),
            "motif_db_json": str(args.motif_db_json.resolve()) if args.motif_db_json else "",
        },
        "outputs": {
            "defect_thermo_table": str(table),
            "calphad_defect_species": str(species),
            "moose_template": str(moose),
        },
        "material": args.material,
        "n_defects": len(rows),
        "notes": [
            "The export keeps DFT defect motifs, valence/magmom labels, formation energies, volumes/eigenstrain, and migration barriers together.",
            "Use the CALPHAD species table for statistical defect thermodynamics and the MOOSE template for defect-property coupling.",
        ],
    }
    write_json(outdir / "defect_thermo_metadata.json", metadata)
    print(f"Wrote defect thermodynamics table: {table}")
    print(f"Wrote MOOSE defect template: {moose}")
    return metadata


if __name__ == "__main__":
    main()
