"""Optional GSAS-II bridge for Bragg/XRD fitting workflows.

Atomi keeps GSAS-II outside the base dependency set.  This module discovers a
configured GSAS-II Python runtime, writes reproducible scriptable refinement
projects, optionally runs them, and collects compact JSON summaries.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Any


GSASII_SCRIPT_TEMPLATE = r'''#!/usr/bin/env python3
"""GSAS-II Bragg/XRD fit script generated by Atomi.

This script uses GSASII.GSASIIscriptable and is intentionally editable.  Start
with conservative refinement stages, inspect the .gpx in GSAS-II, then broaden
the recipe only when the data/instrument model supports it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEFAULT_GSASII_ROOT = {gsasii_root!r}


def add_gsasii_path(root: str | None) -> None:
    if not root:
        return
    p = Path(root).expanduser()
    candidates = [p / "GSAS-II", p]
    for item in candidates:
        if (item / "GSASII" / "GSASIIscriptable.py").exists():
            sys.path.insert(0, str(item))
            return


def build_refinements(args: argparse.Namespace) -> list[dict]:
    first = {
        "set": {
            "Background": {
                "type": args.background_type,
                "no. coeffs": args.background_coeffs,
                "refine": True,
            },
            "Sample Parameters": ["Scale"],
        }
    }
    if args.tth_min is not None or args.tth_max is not None:
        low = args.tth_min if args.tth_min is not None else 0.0
        high = args.tth_max if args.tth_max is not None else 180.0
        first["set"]["Limits"] = [low, high]
    refinements = [first]
    if args.refine_cell:
        refinements.append({"set": {"Cell": True}})
    sample = []
    if args.refine_sample_displacement:
        sample.extend(["DisplaceX", "DisplaceY"])
    if sample:
        refinements.append({"set": {"Sample Parameters": sample}})
    if args.refine_zero:
        refinements.append({"set": {"Instrument Parameters": ["Zero"]}})
    if args.refine_profile:
        refinements.append({"set": {"Instrument Parameters": ["U", "V", "W", "X", "Y"]}})
    return refinements


def summarize_project(gpx, summary_json: Path) -> dict:
    histograms = []
    for hist in gpx.histograms():
        histograms.append(
            {
                "name": hist.name,
                "residuals": hist.residuals,
                "sample_parameters": hist.SampleParameters,
            }
        )
    phases = []
    for phase in gpx.phases():
        phases.append({"name": phase.name, "cell": phase.get_cell()})
    summary = {
        "schema": "atomi.gsasii_bragg_fit_summary.v1",
        "gpx": str(Path(gpx.filename).resolve()),
        "histograms": histograms,
        "phases": phases,
    }
    summary_json.write_text(json.dumps(summary, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gsasii-root", default=DEFAULT_GSASII_ROOT)
    parser.add_argument("--project", default={project!r})
    parser.add_argument("--histogram", default={histogram!r})
    parser.add_argument("--instrument", default={instrument!r})
    parser.add_argument("--phase", default={phase!r})
    parser.add_argument("--phase-name", default={phase_name!r})
    parser.add_argument("--histogram-format", default={histogram_format!r})
    parser.add_argument("--phase-format", default={phase_format!r})
    parser.add_argument("--summary-json", default={summary_json!r})
    parser.add_argument("--background-type", default={background_type!r})
    parser.add_argument("--background-coeffs", type=int, default={background_coeffs})
    parser.add_argument("--tth-min", type=float, default={tth_min})
    parser.add_argument("--tth-max", type=float, default={tth_max})
    parser.add_argument("--refine-cell", action=argparse.BooleanOptionalAction, default={refine_cell})
    parser.add_argument("--refine-profile", action=argparse.BooleanOptionalAction, default={refine_profile})
    parser.add_argument("--refine-zero", action=argparse.BooleanOptionalAction, default={refine_zero})
    parser.add_argument("--refine-sample-displacement", action=argparse.BooleanOptionalAction, default={refine_sample_displacement})
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    add_gsasii_path(args.gsasii_root)
    from GSASII import GSASIIscriptable as G2sc

    try:
        G2sc.SetPrintLevel("warn")
    except Exception:
        pass

    out_project = Path(args.project).expanduser().resolve()
    out_project.parent.mkdir(parents=True, exist_ok=True)
    gpx = G2sc.G2Project(newgpx=str(out_project))
    hist = gpx.add_powder_histogram(
        str(Path(args.histogram).expanduser()),
        str(Path(args.instrument).expanduser()) if args.instrument else None,
        fmthint=args.histogram_format or None,
    )
    gpx.add_phase(
        str(Path(args.phase).expanduser()),
        phasename=args.phase_name or None,
        histograms=[hist],
        fmthint=args.phase_format or None,
    )
    gpx.save()

    refinements = build_refinements(args)
    if args.dry_run:
        print(json.dumps({"project": str(out_project), "refinements": refinements}, indent=2))
        return

    gpx.do_refinements(refinements, makeBack=True)
    gpx.save()
    summary = summarize_project(gpx, Path(args.summary_json).expanduser().resolve())
    print(json.dumps(summary, indent=2, sort_keys=True, default=str))


if __name__ == "__main__":
    main()
'''


COLLECT_CODE = r'''
from __future__ import annotations
import json, sys
from pathlib import Path
root = {root!r}
if root:
    p = Path(root).expanduser()
    for item in (p / "GSAS-II", p):
        if (item / "GSASII" / "GSASIIscriptable.py").exists():
            sys.path.insert(0, str(item))
            break
from GSASII import GSASIIscriptable as G2sc
gpx = G2sc.G2Project({gpx!r})
histograms = [{"name": h.name, "residuals": h.residuals, "sample_parameters": h.SampleParameters} for h in gpx.histograms()]
phases = [{"name": p.name, "cell": p.get_cell()} for p in gpx.phases()]
print(json.dumps({"schema": "atomi.gsasii_bragg_fit_summary.v1", "gpx": str(Path(gpx.filename).resolve()), "histograms": histograms, "phases": phases}, sort_keys=True, default=str))
'''


def _json_dump(data: Any, path: Path | None = None) -> None:
    text = json.dumps(data, indent=2, sort_keys=True)
    if path is not None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text + "\n", encoding="utf-8")
    print(text)


def _prepend_pythonpath(env: dict[str, str], gsasii_root: str | None) -> dict[str, str]:
    if not gsasii_root:
        return env
    root = Path(gsasii_root).expanduser()
    candidates = [root / "GSAS-II", root]
    additions = [str(path) for path in candidates if (path / "GSASII" / "GSASIIscriptable.py").exists()]
    if additions:
        current = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = os.pathsep.join(additions + ([current] if current else []))
    return env


def default_gsasii_python() -> str:
    env_python = os.environ.get("ATOMI_GSASII_PYTHON")
    if env_python:
        return env_python
    env_path = os.environ.get("ATOMI_GSASII_ENV")
    if env_path:
        candidate = Path(env_path).expanduser() / "bin" / "python"
        if candidate.exists():
            return str(candidate)
    return sys.executable


def default_gsasii_root() -> str | None:
    return os.environ.get("ATOMI_GSASII_ROOT")


def probe_gsasii(python: str | None = None, gsasii_root: str | None = None) -> dict[str, Any]:
    py = python or default_gsasii_python()
    root = gsasii_root or default_gsasii_root()
    env = _prepend_pythonpath(os.environ.copy(), root)
    code = (
        "import json; "
        "payload={'available': False}; "
        "\ntry:\n"
        " import GSASII.GSASIIscriptable as G2sc\n"
        " payload={'available': True, 'origin': getattr(G2sc, '__file__', None), 'has_G2Project': hasattr(G2sc, 'G2Project')}\n"
        "except Exception as exc:\n"
        " payload={'available': False, 'error': str(exc), 'error_type': type(exc).__name__}\n"
        "print(json.dumps(payload))\n"
    )
    try:
        proc = subprocess.run([py, "-c", code], text=True, capture_output=True, check=False, env=env)
    except OSError as exc:
        return {"available": False, "python": py, "gsasii_root": root, "error": str(exc)}
    try:
        payload = json.loads((proc.stdout or "{}").strip().splitlines()[-1])
    except (json.JSONDecodeError, IndexError):
        payload = {"available": False, "error": proc.stderr.strip() or proc.stdout.strip()}
    payload.update({"python": py, "gsasii_root": root, "returncode": proc.returncode})
    if proc.stderr.strip():
        payload["stderr"] = proc.stderr.strip()
    return payload


def status_main(args: argparse.Namespace) -> dict[str, Any]:
    report = {
        "schema": "atomi.gsasii_status.v1",
        "gsasii": probe_gsasii(args.python, args.gsasii_root),
        "environment": {
            "ATOMI_GSASII_PYTHON": os.environ.get("ATOMI_GSASII_PYTHON", ""),
            "ATOMI_GSASII_ROOT": os.environ.get("ATOMI_GSASII_ROOT", ""),
            "ATOMI_GSASII_ENV": os.environ.get("ATOMI_GSASII_ENV", ""),
        },
    }
    if args.write:
        _json_dump(report, args.write)
    elif args.json:
        _json_dump(report)
    else:
        gsas = report["gsasii"]
        print("GSAS-II bridge status")
        print(f"  python      : {gsas.get('python')}")
        print(f"  gsasii root : {gsas.get('gsasii_root') or '(not set)'}")
        print(f"  import      : {'ok' if gsas.get('available') else 'missing'}")
        print(f"  origin      : {gsas.get('origin') or gsas.get('error', '')}")
    return report


def render_script(args: argparse.Namespace) -> str:
    project = str((args.outdir / args.project_name).resolve())
    summary_json = str((args.outdir / args.summary_name).resolve())
    values = {
        "{gsasii_root!r}": repr(str(args.gsasii_root or default_gsasii_root() or "")),
        "{project!r}": repr(project),
        "{histogram!r}": repr(str(args.histogram)),
        "{instrument!r}": repr(str(args.instrument or "")),
        "{phase!r}": repr(str(args.phase)),
        "{phase_name!r}": repr(args.phase_name or ""),
        "{histogram_format!r}": repr(args.histogram_format or ""),
        "{phase_format!r}": repr(args.phase_format or ""),
        "{summary_json!r}": repr(summary_json),
        "{background_type!r}": repr(args.background_type),
        "{background_coeffs}": str(args.background_coeffs),
        "{tth_min}": "None" if args.tth_min is None else repr(args.tth_min),
        "{tth_max}": "None" if args.tth_max is None else repr(args.tth_max),
        "{refine_cell}": repr(args.refine_cell),
        "{refine_profile}": repr(args.refine_profile),
        "{refine_zero}": repr(args.refine_zero),
        "{refine_sample_displacement}": repr(args.refine_sample_displacement),
    }
    script = GSASII_SCRIPT_TEMPLATE
    for token, value in values.items():
        script = script.replace(token, value)
    return script


def write_project_main(args: argparse.Namespace) -> dict[str, Any]:
    args.outdir.mkdir(parents=True, exist_ok=True)
    script_path = args.outdir / args.script_name
    script_path.write_text(render_script(args), encoding="utf-8")
    script_path.chmod(0o755)
    run_script = args.outdir / "run_gsasii_xrd_fit.sh"
    python = args.python or default_gsasii_python()
    gsasii_root = args.gsasii_root or default_gsasii_root()
    exports = []
    if gsasii_root:
        exports.append(f"export ATOMI_GSASII_ROOT={shlex.quote(str(gsasii_root))}")
    exports.append(f"export ATOMI_GSASII_PYTHON={shlex.quote(str(python))}")
    run_script.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        'cd "${SCRIPT_DIR}"\n'
        + "\n".join(exports)
        + "\n"
        + shlex.quote(str(python))
        + " "
        + shlex.quote(str(script_path.name))
        + "\n",
        encoding="utf-8",
    )
    run_script.chmod(0o755)
    metadata = {
        "schema": "atomi.gsasii_bridge_project.v1",
        "backend": "GSAS-II scriptable Bragg/Rietveld fitting",
        "script": str(script_path.resolve()),
        "run_script": str(run_script.resolve()),
        "project": str((args.outdir / args.project_name).resolve()),
        "summary_json": str((args.outdir / args.summary_name).resolve()),
        "histogram": str(args.histogram),
        "instrument": str(args.instrument) if args.instrument else "",
        "phase": str(args.phase),
        "notes": [
            "GSAS-II is external; configure ATOMI_GSASII_PYTHON and ATOMI_GSASII_ROOT or use confighpc.",
            "Default recipe refines background and scale, then optional cell/profile/zero terms.",
            "Inspect the .gpx and residuals before broadening refinement flags for publication fits.",
        ],
    }
    (args.outdir / "gsasii_bridge_project.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote GSAS-II fit script: {script_path}")
    print(f"Wrote run script: {run_script}")
    return metadata


def run_main(args: argparse.Namespace) -> dict[str, Any]:
    metadata = write_project_main(args)
    python = args.python or default_gsasii_python()
    env = _prepend_pythonpath(os.environ.copy(), args.gsasii_root or default_gsasii_root())
    proc = subprocess.run(
        [python, Path(metadata["script"]).name],
        cwd=args.outdir,
        text=True,
        capture_output=True,
        check=False,
        env=env,
    )
    logs = args.outdir / "logs"
    logs.mkdir(exist_ok=True)
    (logs / "gsasii_xrd_fit.stdout.log").write_text(proc.stdout, encoding="utf-8")
    (logs / "gsasii_xrd_fit.stderr.log").write_text(proc.stderr, encoding="utf-8")
    metadata["run"] = {"returncode": proc.returncode, "stdout_log": str(logs / "gsasii_xrd_fit.stdout.log"), "stderr_log": str(logs / "gsasii_xrd_fit.stderr.log")}
    (args.outdir / "gsasii_bridge_project.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    if proc.returncode != 0:
        raise RuntimeError(f"GSAS-II script failed; see {logs}")
    return metadata


def collect_main(args: argparse.Namespace) -> dict[str, Any]:
    python = args.python or default_gsasii_python()
    root = args.gsasii_root or default_gsasii_root()
    code = COLLECT_CODE.replace("{root!r}", repr(str(root or ""))).replace(
        "{gpx!r}", repr(str(args.gpx.expanduser().resolve()))
    )
    env = _prepend_pythonpath(os.environ.copy(), root)
    proc = subprocess.run([python, "-c", code], text=True, capture_output=True, check=False, env=env)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or proc.stdout.strip() or "GSAS-II collect failed")
    summary = json.loads(proc.stdout.strip().splitlines()[-1] if "\n" in proc.stdout else proc.stdout)
    if args.write:
        _json_dump(summary, args.write)
    else:
        _json_dump(summary)
    return summary


def install_plan_main(args: argparse.Namespace) -> dict[str, Any]:
    payload = {
        "recommendation": "Keep GSAS-II in a separate conda/GSAS-II runtime and call it from the Atomi environment.",
        "why": [
            "GSAS-II carries GUI/binary/scientific-stack dependencies that can disturb a stable LAMMPS/VASP environment.",
            "Atomi only needs the GSAS-II Python executable and source root to drive scriptable Bragg fits.",
            "No GPU allocation is needed for GSAS-II installation or routine Rietveld refinement.",
        ],
        "hpc_pattern": [
            "Install GSAS-II in ~/atomi_hpc/gsas2main or a project software area.",
            "Record python/root in ~/atomi_hpc/atomi_hpc_config.kit.local.json under profiles.gsasii.",
            "Apply with: eval \"$(confighpc --config ~/atomi_hpc/atomi_hpc_config.kit.local.json --shell)\"",
            "Check with: gsasii-status",
        ],
        "example_profile": {
            "profiles": {
                "gsasii": {
                    "env_path": "$HOME/atomi_hpc/gsas2main",
                    "python": "$HOME/atomi_hpc/gsas2main/bin/python",
                    "root": "$HOME/atomi_hpc/gsas2main",
                    "environment": {
                        "ATOMI_GSASII_PYTHON": "$HOME/atomi_hpc/gsas2main/bin/python",
                        "ATOMI_GSASII_ROOT": "$HOME/atomi_hpc/gsas2main",
                    },
                }
            }
        },
    }
    if args.json:
        _json_dump(payload)
    else:
        print("GSAS-II / Atomi HPC install plan")
        for line in payload["why"]:
            print(f"  - {line}")
        print("  Recommended: separate GSAS-II runtime, configured through private KIT JSON.")
    return payload


def add_common_fit_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--histogram", type=Path, required=True, help="Experimental powder data file, e.g. .xy/.xye/.fxye.")
    parser.add_argument("--instrument", type=Path, help="GSAS-II instrument parameter file. Some importers can provide this.")
    parser.add_argument("--phase", type=Path, required=True, help="CIF/POSCAR/phase file for the starting structure.")
    parser.add_argument("--outdir", type=Path, default=Path("gsasii_xrd_fit"))
    parser.add_argument("--python", help="GSAS-II Python executable. Defaults to ATOMI_GSASII_PYTHON or active Python.")
    parser.add_argument("--gsasii-root", help="GSAS-II install root, e.g. ~/gsas2main. Defaults to ATOMI_GSASII_ROOT.")
    parser.add_argument("--script-name", default="run_gsasii_xrd_fit.py")
    parser.add_argument("--project-name", default="atomi_gsasii_xrd_fit.gpx")
    parser.add_argument("--summary-name", default="gsasii_xrd_fit_summary.json")
    parser.add_argument("--phase-name")
    parser.add_argument("--histogram-format", help="Optional GSAS-II importer format hint for powder data.")
    parser.add_argument("--phase-format", help="Optional GSAS-II importer format hint for phase data.")
    parser.add_argument("--background-type", default="chebyschev-1")
    parser.add_argument("--background-coeffs", type=int, default=3)
    parser.add_argument("--tth-min", type=float)
    parser.add_argument("--tth-max", type=float)
    parser.add_argument("--refine-cell", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--refine-profile", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--refine-zero", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--refine-sample-displacement", action=argparse.BooleanOptionalAction, default=False)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("status", "doctor"):
        p = sub.add_parser(name, help="Check GSAS-II scriptable availability.")
        p.add_argument("--python")
        p.add_argument("--gsasii-root")
        p.add_argument("--json", action="store_true")
        p.add_argument("--write", type=Path)
        p.set_defaults(func=status_main)
    p = sub.add_parser("install-plan", help="Print recommended HPC installation/configuration pattern.")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=install_plan_main)
    p = sub.add_parser("write-script", help="Write a GSAS-II scriptable Bragg/Rietveld fit project.")
    add_common_fit_args(p)
    p.set_defaults(func=write_project_main)
    p = sub.add_parser("run", help="Write and run a GSAS-II scriptable Bragg/Rietveld fit project.")
    add_common_fit_args(p)
    p.set_defaults(func=run_main)
    p = sub.add_parser("collect", help="Collect residual/cell summary from an existing .gpx project.")
    p.add_argument("--gpx", type=Path, required=True)
    p.add_argument("--python")
    p.add_argument("--gsasii-root")
    p.add_argument("--write", type=Path)
    p.set_defaults(func=collect_main)
    return parser


def main(argv: list[str] | None = None) -> Any:
    args = build_parser().parse_args(argv)
    return args.func(args)


def status_cli() -> Any:
    return main(["status", *sys.argv[1:]])


def install_plan_cli() -> Any:
    return main(["install-plan", *sys.argv[1:]])


if __name__ == "__main__":
    main()
