"""Bridge helpers for PDF refinement backends.

This module does not try to hide the fact that PDF programs use related but
different real-space functions.  It records the convention up front, then
creates backend-specific launch material for DiffPy/PDFgui-style small-box
refinement and RMCProfile-style large-box refinement.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import textwrap
from importlib import util as importlib_util
from pathlib import Path
from typing import Any


FUNCTION_DEFINITIONS: list[dict[str, str]] = [
    {
        "symbol": "S(Q)",
        "domain": "reciprocal",
        "definition": "Total scattering structure function after corrections and normalization.",
        "common_use": "Input to Fourier transforms and reciprocal-space RMCProfile terms.",
        "guardrail": "State whether Bragg peaks, diffuse scattering, or both are included.",
    },
    {
        "symbol": "F(Q)",
        "domain": "reciprocal",
        "definition": "Reduced total scattering function, commonly F(Q) = Q * (S(Q) - 1).",
        "common_use": "PDFgetX/PDFgui and DiffPy workflows usually transform F(Q) to G(r).",
        "guardrail": "Q weighting and Qmax/Qmin/windowing control termination ripples.",
    },
    {
        "symbol": "g(r)",
        "domain": "real",
        "definition": "Dimensionless radial distribution function; tends to 1 at large r for a homogeneous material.",
        "common_use": "MD/RDF analysis and some RMC outputs.",
        "guardrail": "Partial g_ab(r) must be combined with the same scattering weights used by the experiment.",
    },
    {
        "symbol": "G(r)",
        "domain": "real",
        "definition": "Reduced PDF, commonly G(r) = 4*pi*r*rho0*(g(r)-1) = (2/pi) integral Q[S(Q)-1] sin(Qr) dQ.",
        "common_use": "PDFgetX, PDFgui, DiffPy srfit/pdffit2, and many xPDF reports.",
        "guardrail": "Check rho0, composition, scattering type, Qmax, and damping/broadening before comparing amplitudes.",
    },
    {
        "symbol": "T(r)",
        "domain": "real",
        "definition": "Total radial distribution/correlation function used by RMCProfile documentation and Keen-style discussion.",
        "common_use": "RMCProfile can compare a real-space T(r)-like term alongside S(Q) and Bragg profiles.",
        "guardrail": "RMCProfile allows multiple normalizations; record the exact input convention rather than assuming T(r)=G(r).",
    },
    {
        "symbol": "D(r)",
        "domain": "real",
        "definition": "Backend-specific total/differential correlation notation; meaning varies across PDF/RMC programs.",
        "common_use": "Some manuals and legacy scripts use D(r) for transformed or differential PDF-like data.",
        "guardrail": "Do not auto-convert D(r) to G(r) or T(r) without an explicit manual-backed convention.",
    },
    {
        "symbol": "I(t) / Bragg profile",
        "domain": "reciprocal/time-of-flight",
        "definition": "Powder diffraction profile term used by RMCProfile for crystalline materials.",
        "common_use": "Large-box RMCProfile refinement of average structure plus diffuse/local structure.",
        "guardrail": "Keep instrument resolution and bank/profile parameters with the project metadata.",
    },
]


DIFFPY_TEMPLATE = r'''#!/usr/bin/env python3
"""DiffPy small-box PDF fitting template generated by atomi pdf-fit-bridge.

Inputs are assumed to use the reduced PDF convention:
    G(r) = 4*pi*r*rho0*(g(r)-1)
         = (2/pi) integral Q[S(Q)-1] sin(Qr) dQ.

This script is intentionally compact and editable.  It targets the DiffPy
srfit pattern used by PDFgui-like refinements: one structure model fitted to
an experimental G(r), with scale and PDF instrumental parameters refined.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--structure", default={structure!r})
    parser.add_argument("--data", default={data!r}, help="Two-column r, G(r) file.")
    parser.add_argument("--out", default="diffpy_fit_result.xy")
    parser.add_argument("--rmin", type=float, default={rmin})
    parser.add_argument("--rmax", type=float, default={rmax})
    parser.add_argument("--qmax", type=float, default={qmax})
    parser.add_argument("--qdamp", type=float, default={qdamp})
    parser.add_argument("--qbroad", type=float, default={qbroad})
    parser.add_argument("--delta2", type=float, default={delta2})
    parser.add_argument("--scale", type=float, default=1.0)
    args = parser.parse_args()

    try:
        from diffpy.structure import load_structure
        from diffpy.structure.structureerrors import StructureFormatError
        from diffpy.srfit.fitbase import FitRecipe, FitResults
        from diffpy.srfit.pdf import PDFContribution, PDFGenerator
        from scipy.optimize import least_squares
    except Exception as exc:
        raise SystemExit(
            "Missing DiffPy/scipy backend. Install in the active env with: "
            "python -m pip install diffpy.structure diffpy.srfit diffpy.pdffit2 diffpy.srreal scipy"
        ) from exc

    structure_path = Path(args.structure)
    data_path = Path(args.data)
    if not structure_path.exists():
        raise SystemExit(f"Structure not found: {structure_path}")
    if not data_path.exists():
        raise SystemExit(f"Experimental G(r) data not found: {data_path}")

    contribution = PDFContribution("pdf")
    contribution.loadData(str(data_path))
    contribution.setCalculationRange(xmin=args.rmin, xmax=args.rmax, dx=None)

    generator = PDFGenerator("G")
    structure = None
    structure_name = structure_path.name.upper()
    vasp_like = "POSCAR" in structure_name or "CONTCAR" in structure_name or structure_path.suffix.upper() in {
        ".POSCAR",
        ".CONTCAR",
    }
    if not vasp_like:
        try:
            structure = load_structure(str(structure_path))
        except StructureFormatError:
            structure = None
    if structure is None:
        try:
            from ase.io import read, write
        except Exception as exc:
            raise SystemExit(
                "DiffPy could not parse the structure directly. Install ASE or provide CIF/PDFfit/XCFG input."
            ) from exc
        converted = structure_path.with_suffix(structure_path.suffix + ".atomi_tmp.cif")
        try:
            atoms = read(str(structure_path), format="vasp")
        except Exception:
            atoms = read(str(structure_path))
        write(str(converted), atoms, format="cif")
        structure = load_structure(str(converted))
    generator.setStructure(structure)
    generator.setQmax(args.qmax)
    contribution.addProfileGenerator(generator)
    contribution.setEquation("scale * G")

    recipe = FitRecipe()
    recipe.addContribution(contribution)
    recipe.addVar(contribution.scale, args.scale, name="scale")
    recipe.addVar(generator.qdamp, args.qdamp, name="qdamp")
    recipe.addVar(generator.qbroad, args.qbroad, name="qbroad")
    recipe.addVar(generator.delta2, args.delta2, name="delta2")

    result = least_squares(recipe.residual, recipe.getValues(), xtol=1e-8, ftol=1e-8, gtol=1e-8)
    try:
        recipe.setValues(result.x)
    except AttributeError:
        recipe._applyValues(result.x)
    FitResults(recipe).printResults()

    r = contribution.profile.x
    gobs = contribution.profile.y
    gcalc = contribution.evaluate()
    np.savetxt(
        args.out,
        np.column_stack([r, gobs, gcalc, gobs - gcalc]),
        header="r Gobs Gcalc Gdiff ; reduced PDF G(r) convention",
    )
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
'''


def _json_dump(data: Any, path: Path | None = None) -> None:
    text = json.dumps(data, indent=2, sort_keys=True)
    if path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text + "\n", encoding="utf-8")
    print(text)


def _python_import_status(module: str, python: str | None = None) -> dict[str, Any]:
    if python:
        code = (
            "import importlib.util, json; "
            f"spec = importlib.util.find_spec({module!r}); "
            "print(json.dumps({'available': spec is not None, 'origin': getattr(spec, 'origin', None) if spec else None}))"
        )
        try:
            proc = subprocess.run(
                [python, "-c", code],
                text=True,
                capture_output=True,
                check=False,
            )
        except OSError as exc:
            return {"available": False, "error": str(exc), "python": python}
        if proc.returncode != 0:
            return {"available": False, "error": proc.stderr.strip(), "python": python}
        try:
            payload = json.loads(proc.stdout.strip() or "{}")
        except json.JSONDecodeError:
            payload = {"available": False, "error": proc.stdout.strip()}
        payload["python"] = python
        return payload

    try:
        spec = importlib_util.find_spec(module)
    except ModuleNotFoundError:
        spec = None
    return {
        "available": spec is not None,
        "origin": getattr(spec, "origin", None) if spec else None,
        "python": sys.executable,
    }


def _executable_status(names: list[str], env_var: str | None = None) -> dict[str, Any]:
    candidates: list[str] = []
    env_value = os.environ.get(env_var) if env_var else None
    if env_value:
        candidates.append(env_value)
    candidates.extend(names)
    for candidate in candidates:
        found = shutil.which(candidate)
        if found:
            return {"available": True, "path": found, "source": env_var if candidate == env_value else "PATH"}
        if Path(candidate).exists():
            return {"available": True, "path": str(Path(candidate).resolve()), "source": env_var or "path"}
    return {"available": False, "checked": candidates, "env_var": env_var}


def build_status(python: str | None = None) -> dict[str, Any]:
    return {
        "python": python or sys.executable,
        "diffpy": {
            "diffpy.structure": _python_import_status("diffpy.structure", python),
            "diffpy.srfit": _python_import_status("diffpy.srfit", python),
            "diffpy.pdffit2": _python_import_status("diffpy.pdffit2", python),
            "diffpy.srreal": _python_import_status("diffpy.srreal", python),
        },
        "executables": {
            "pdfgui": _executable_status(["pdfgui", "PDFgui"], "ATOMI_PDFGUI_EXE"),
            "rmcprofile": _executable_status(
                ["rmcprofile", "RMCProfile", "rmcprofile.x", "rmcprofile_mpi", "RMCProfile_mpi"],
                "ATOMI_RMCPROFILE_EXE",
            ),
        },
        "definition_guard": "Always declare whether input data are G(r), T(r), D(r), g(r), F(Q), or S(Q).",
    }


def print_status(args: argparse.Namespace) -> None:
    status = build_status(args.python)
    if args.write:
        _json_dump(status, Path(args.write))
        return
    if args.json:
        _json_dump(status)
        return
    print("PDF fitting backend status")
    print(f"  Python: {status['python']}")
    for name, payload in status["diffpy"].items():
        flag = "ok" if payload.get("available") else "missing"
        origin = payload.get("origin") or payload.get("error") or ""
        print(f"  {name}: {flag} {origin}")
    for name, payload in status["executables"].items():
        flag = "ok" if payload.get("available") else "missing"
        detail = payload.get("path") or ", ".join(payload.get("checked", []))
        print(f"  {name}: {flag} {detail}")
    print(f"  Guard: {status['definition_guard']}")


def print_definitions(args: argparse.Namespace) -> None:
    payload = {"definitions": FUNCTION_DEFINITIONS}
    if args.write:
        _json_dump(payload, Path(args.write))
        return
    if args.json:
        _json_dump(payload)
        return
    print("PDF function definitions and guardrails")
    for item in FUNCTION_DEFINITIONS:
        print(f"\n{item['symbol']} ({item['domain']})")
        print(f"  definition: {item['definition']}")
        print(f"  common use: {item['common_use']}")
        print(f"  guardrail: {item['guardrail']}")


def write_diffpy_script(args: argparse.Namespace) -> None:
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    script_path = outdir / args.script_name
    script = DIFFPY_TEMPLATE
    replacements = {
        "{structure!r}": repr(str(args.structure)),
        "{data!r}": repr(str(args.exp)),
        "{rmin}": str(args.rmin),
        "{rmax}": str(args.rmax),
        "{qmax}": str(args.qmax),
        "{qdamp}": str(args.qdamp),
        "{qbroad}": str(args.qbroad),
        "{delta2}": str(args.delta2),
    }
    for token, value in replacements.items():
        script = script.replace(token, value)
    script_path.write_text(script, encoding="utf-8")
    script_path.chmod(0o755)
    metadata = {
        "backend": "DiffPy srfit / PDFgui-style small-box refinement",
        "structure": str(args.structure),
        "experiment": str(args.exp),
        "quantity": "G(r)",
        "definition": next(item["definition"] for item in FUNCTION_DEFINITIONS if item["symbol"] == "G(r)"),
        "rmin": args.rmin,
        "rmax": args.rmax,
        "qmax": args.qmax,
        "notes": [
            "Template assumes reduced PDF G(r).",
            "Use this for small-box structure refinement or static DFT/POSCAR/CIF comparison.",
            "For real publication fits, verify DiffPy parameter names against the installed DiffPy version.",
        ],
    }
    (outdir / "pdf_fit_convention.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {script_path}")
    print(f"Wrote {outdir / 'pdf_fit_convention.json'}")


def write_rmcprofile_project(args: argparse.Namespace) -> None:
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    inputs = outdir / "inputs"
    inputs.mkdir(exist_ok=True)
    metadata = {
        "backend": "RMCProfile-style large-box refinement",
        "structure": str(args.structure) if args.structure else None,
        "real_space_data": str(args.real_space_data) if args.real_space_data else None,
        "reciprocal_space_data": str(args.sq_data) if args.sq_data else None,
        "bragg_profile": str(args.bragg_profile) if args.bragg_profile else None,
        "declared_real_space_function": args.real_space_function,
        "function_definitions": FUNCTION_DEFINITIONS,
        "guardrails": [
            "Keep the measured function normalization with the project.",
            "For Keen/RMCProfile workflows, T(r), S(Q), and Bragg/profile terms can be fitted together.",
            "Do not mix a PDFgui G(r) file into a T(r) slot without conversion and documentation.",
            "Use large supercells for configurational/local-structure questions; reserve PDFgui/DiffPy for small-box refinements.",
        ],
    }
    (outdir / "atomi_rmcprofile_project.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    readme = f"""# RMCProfile bridge project

Generated by `atomi pdf-fit-bridge write-rmcprofile-project`.

## Declared data convention

Real-space function: `{args.real_space_function}`

RMCProfile and Keen-style workflows may compare real-space radial distribution
terms, reciprocal-space S(Q), and Bragg/profile terms together.  The exact
normalization is not interchangeable with PDFgui/DiffPy G(r) unless converted.

## Next manual inputs

- Put RMCProfile control files in `inputs/`.
- Set `ATOMI_RMCPROFILE_EXE` if the executable is not on PATH.
- Keep instrument resolution/profile-bank files next to the data.
- Record any conversion from G(r), g(r), D(r), or T(r) in
  `atomi_rmcprofile_project.json`.

## Suggested command pattern

```bash
$ATOMI_RMCPROFILE_EXE < your_project.rmc
```
"""
    (outdir / "README.md").write_text(readme, encoding="utf-8")
    print(f"Wrote {outdir / 'atomi_rmcprofile_project.json'}")
    print(f"Wrote {outdir / 'README.md'}")


def print_install_plan(args: argparse.Namespace) -> None:
    env_python = str(Path(args.env).expanduser() / "bin" / "python")
    payload = {
        "diffpy_core": {
            "purpose": "Small-box PDF fitting and PDFgui-style scripted refinement.",
            "command": f"{env_python} -m pip install diffpy.structure diffpy.srfit diffpy.pdffit2 diffpy.srreal scipy",
            "note": "diffpy.srreal is required by PDFGenerator. If pip source builds fail, install Boost and set BOOST_PATH, or use the micromamba DiffPy PDF environment.",
        },
        "pdfgui": {
            "purpose": "GUI small-box refinement front-end.",
            "note": "PDFgui is normally distributed through xPDFsuite/conda/desktop installers, not as a plain pip package.",
            "atomi_bridge": "Use DiffPy scripts for headless HPC fits; keep GUI PDFgui on a workstation if needed.",
        },
        "rmcprofile": {
            "purpose": "Large-box RMCProfile refinement with S(Q), real-space correlation, and Bragg/profile terms.",
            "note": "RMCProfile is an external compiled executable; install/module-load it separately and set ATOMI_RMCPROFILE_EXE.",
        },
    }
    if args.json:
        _json_dump(payload)
        return
    print("Recommended install/configuration plan")
    print(f"  DiffPy core: {payload['diffpy_core']['command']}")
    print(f"  PDFgui: {payload['pdfgui']['note']}")
    print(f"  RMCProfile: {payload['rmcprofile']['note']}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="atomi pdf-fit-bridge",
        description="Bridge Atomi to DiffPy/PDFgui-style and RMCProfile-style PDF fitting workflows.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    for name in ("status", "doctor"):
        status_parser = subparsers.add_parser(name, help="Check DiffPy/PDFgui/RMCProfile backend availability.")
        status_parser.add_argument("--python", default=None, help="Python interpreter to inspect, e.g. ~/m_lammps_env/bin/python.")
        status_parser.add_argument("--json", action="store_true")
        status_parser.add_argument("--write", default=None, help="Optional JSON output path.")
        status_parser.set_defaults(func=print_status)

    definitions = subparsers.add_parser("definitions", help="Print PDF/RDF function definitions and guardrails.")
    definitions.add_argument("--json", action="store_true")
    definitions.add_argument("--write", default=None, help="Optional JSON output path.")
    definitions.set_defaults(func=print_definitions)

    diffpy = subparsers.add_parser("write-diffpy-script", help="Create a DiffPy small-box G(r) fitting template.")
    diffpy.add_argument("--structure", required=True, help="CIF/POSCAR/structure file accepted by diffpy.structure.")
    diffpy.add_argument("--exp", required=True, help="Experimental two-column r, G(r) file.")
    diffpy.add_argument("--outdir", default="pdf_fit_diffpy_project")
    diffpy.add_argument("--script-name", default="run_diffpy_pdf_fit.py")
    diffpy.add_argument("--rmin", type=float, default=1.5)
    diffpy.add_argument("--rmax", type=float, default=20.0)
    diffpy.add_argument("--qmax", type=float, default=25.0)
    diffpy.add_argument("--qdamp", type=float, default=0.04)
    diffpy.add_argument("--qbroad", type=float, default=0.02)
    diffpy.add_argument("--delta2", type=float, default=2.0)
    diffpy.set_defaults(func=write_diffpy_script)

    rmc = subparsers.add_parser("write-rmcprofile-project", help="Create a guarded RMCProfile large-box project skeleton.")
    rmc.add_argument("--outdir", default="pdf_fit_rmcprofile_project")
    rmc.add_argument("--structure", default=None)
    rmc.add_argument("--real-space-data", default=None)
    rmc.add_argument("--sq-data", default=None)
    rmc.add_argument("--bragg-profile", default=None)
    rmc.add_argument("--real-space-function", default="T(r)", choices=("T(r)", "G(r)", "D(r)", "g(r)"))
    rmc.set_defaults(func=write_rmcprofile_project)

    install_plan = subparsers.add_parser("install-plan", help="Print installation guidance for the fitting backends.")
    install_plan.add_argument("--env", default="~/m_lammps_env")
    install_plan.add_argument("--json", action="store_true")
    install_plan.set_defaults(func=print_install_plan)

    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    args.func(args)
