"""Export CALPHAD/free-energy tables for MOOSE-facing workflows."""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from pathlib import Path
from typing import Any

from atomi.calphad.env import inspect_calphad_environment


def finite_float(value: Any) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    return number if math.isfinite(number) else None


def safe_name(value: str) -> str:
    return re.sub(r"[^0-9A-Za-z_]+", "_", value.strip()).strip("_") or "phase"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def format_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if not math.isfinite(number):
        return ""
    return f"{number:.12g}"


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: format_value(row.get(field)) for field in fields})


def normalize_rows(rows: list[dict[str, str]], *, phase: str | None, material: str) -> tuple[list[dict[str, Any]], list[str]]:
    normalized: list[dict[str, Any]] = []
    extra_fields: list[str] = []
    for row in rows:
        temp = finite_float(row.get("T_K") or row.get("temperature_K") or row.get("T"))
        if temp is None:
            continue
        clean: dict[str, Any] = {
            "T_K": temp,
            "phase": row.get("phase") or phase or material,
            "composition": row.get("composition") or row.get("x") or "",
        }
        for key, value in row.items():
            if key in {"T_K", "temperature_K", "T", "phase", "composition", "x"}:
                continue
            parsed = finite_float(value)
            if parsed is None:
                if value not in (None, ""):
                    clean[key] = value
            else:
                clean[key] = parsed
                if key not in extra_fields:
                    extra_fields.append(key)
        normalized.append(clean)
    return sorted(normalized, key=lambda item: (str(item.get("phase")), float(item["T_K"]))), extra_fields


def series_by_field(rows: list[dict[str, Any]], field: str) -> list[tuple[float, float]]:
    points: list[tuple[float, float]] = []
    for row in rows:
        value = finite_float(row.get(field))
        temp = finite_float(row.get("T_K"))
        if temp is not None and value is not None:
            points.append((temp, value))
    return sorted(points)


def write_moose_template(
    path: Path,
    rows: list[dict[str, Any]],
    *,
    material: str,
    fields: list[str],
    temperature_variable: str,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    prefix = safe_name(material).lower()
    lines = [
        "# MOOSE phase-field/CALPHAD bridge generated by Atomi.",
        "# Units are inherited from the input table; use J/mol and consistent composition units for CALPHAD work.",
        "# This file is a starting template because exact free-energy material kernels depend on the MOOSE app.",
        "",
        "[Functions]",
    ]
    for field in fields:
        points = series_by_field(rows, field)
        if len(points) < 1:
            continue
        function = f"{prefix}_{safe_name(field)}"
        x_values = " ".join(format_value(temp) for temp, _ in points)
        y_values = " ".join(format_value(value) for _, value in points)
        lines.extend(
            [
                f"  [./{function}]",
                "    type = PiecewiseLinear",
                f"    x = '{x_values}'",
                f"    y = '{y_values}'",
                "  [../]",
            ]
        )
    lines.extend(
        [
            "[]",
            "",
            "[Materials]",
            f"  [./{prefix}_calphad_table_bridge]",
            "    type = GenericFunctionMaterial",
            f"    prop_names = '{' '.join(fields)}'",
            f"    prop_values = '{' '.join(f'{prefix}_{safe_name(field)}' for field in fields)}'",
            f"    # temperature variable expected by the functions: {temperature_variable}",
            "    # For phase-field, connect these table functions to DerivativeParsedMaterial",
            "    # or to an application-specific CALPHAD free-energy material.",
            "  [../]",
            "[]",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="calphad_export",
        description="Normalize CALPHAD/pycalphad property tables and write MOOSE free-energy bridge templates.",
    )
    parser.add_argument("--tdb", type=Path, help="Optional TDB path to inspect with pycalphad.")
    parser.add_argument("--property-csv", type=Path, required=True, help="CSV containing T_K and G/mu/Cp/property columns.")
    parser.add_argument("--outdir", type=Path, default=Path("analysis/calphad_export"))
    parser.add_argument("--material", default="material")
    parser.add_argument("--phase", help="Default phase label when the CSV does not include a phase column.")
    parser.add_argument("--component", action="append", default=[], help="Components to record in metadata.")
    parser.add_argument("--export-field", action="append", default=[], help="Fields to expose in the MOOSE include.")
    parser.add_argument("--temperature-variable", default="T")
    return parser


def main(argv: list[str] | None = None) -> dict[str, Any]:
    args = build_parser().parse_args(argv)
    source_rows = read_csv(args.property_csv.resolve())
    rows, numeric_fields = normalize_rows(source_rows, phase=args.phase, material=args.material)
    export_fields = args.export_field or [
        field
        for field in numeric_fields
        if field.startswith(("G", "mu", "Cp", "H", "S", "mobility", "D_", "k_"))
    ]
    fields = ["T_K", "phase", "composition", *numeric_fields]
    outdir = args.outdir.resolve()
    table = outdir / "calphad_property_table.csv"
    write_csv(table, rows, fields)
    include = outdir / f"{safe_name(args.material)}_phase_field_free_energy.i"
    write_moose_template(
        include,
        rows,
        material=args.material,
        fields=export_fields,
        temperature_variable=args.temperature_variable,
    )
    db_report = inspect_calphad_environment(
        database=args.tdb.resolve() if args.tdb else None,
        components=args.component,
        phases=[args.phase] if args.phase else None,
    )
    metadata = {
        "schema": "atomi.calphad.export.v1",
        "inputs": {
            "property_csv": str(args.property_csv.resolve()),
            "tdb": str(args.tdb.resolve()) if args.tdb else "",
        },
        "outputs": {
            "property_table": str(table),
            "moose_template": str(include),
        },
        "material": args.material,
        "phase": args.phase or "",
        "components": args.component,
        "export_fields": export_fields,
        "calphad_environment": db_report,
        "notes": [
            "This command exports tabulated CALPHAD quantities and a MOOSE bridge template.",
            "Exact phase-field free-energy material syntax should be specialized for the target MOOSE app.",
        ],
    }
    write_json(outdir / "calphad_export_metadata.json", metadata)
    print(f"Wrote CALPHAD property table: {table}")
    print(f"Wrote MOOSE phase-field template: {include}")
    return metadata


if __name__ == "__main__":
    main()
