from __future__ import annotations

import argparse
import csv
import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
from ase import Atoms
from ase.io import read, write

from atomi.vasp.prep import (
    DEFAULT_TEMPLATE_FILES,
    resolve_input_poscar,
    species_order_from_atoms,
    summarize_atoms,
    validate_vasp_template,
)

@dataclass
class PhonopyRecord:
    run_dir: Path
    dataset: str
    kind: str
    family: str
    volume_fraction: float
    source_poscar: Path
    info: str


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def copy_vasp_template(template_dir: Path | None, dest_dir: Path, copy_all: bool) -> None:
    if template_dir is None:
        return
    if copy_all:
        for item in sorted(template_dir.iterdir()):
            if item.name == "POSCAR":
                continue
            target = dest_dir / item.name
            if item.is_dir():
                shutil.copytree(item, target, dirs_exist_ok=True)
            elif item.is_file():
                shutil.copy2(item, target)
        return

    for filename in DEFAULT_TEMPLATE_FILES:
        src = template_dir / filename
        if not src.exists():
            raise FileNotFoundError(f"Missing {filename} in template dir: {template_dir}")
        shutil.copy2(src, dest_dir / filename)


def apply_strain(atoms: Atoms, strain_matrix: np.ndarray) -> Atoms:
    result = atoms.copy()
    deformation = np.eye(3) + strain_matrix
    result.set_cell(deformation @ atoms.cell.array, scale_atoms=True)
    return result


def isotropic_strain_matrix(eps: float) -> np.ndarray:
    return np.eye(3) * eps


def make_strain_set(
    hydro_list: Iterable[float],
    eps_uni: float,
    eps_shear: float,
    include_uniaxial: bool,
    include_shear: bool,
) -> list[tuple[str, np.ndarray, str]]:
    strains: list[tuple[str, np.ndarray, str]] = []

    for eps in hydro_list:
        for sign in (+1, -1):
            value = sign * abs(eps)
            name = f"hydro_{'p' if value > 0 else 'm'}{abs(value):.4f}".replace(".", "p")
            strains.append((name, isotropic_strain_matrix(value), "hydro"))

    if include_uniaxial:
        for axis, label in enumerate(("xx", "yy", "zz")):
            for sign in (+1, -1):
                strain = np.zeros((3, 3))
                strain[axis, axis] = sign * eps_uni
                strains.append((f"uni_{label}_{'p' if sign > 0 else 'm'}", strain, "uniaxial"))

    if include_shear:
        for label, (i, j) in (("xy", (0, 1)), ("xz", (0, 2)), ("yz", (1, 2))):
            for sign in (+1, -1):
                strain = np.zeros((3, 3))
                strain[i, j] = 0.5 * sign * eps_shear
                strain[j, i] = 0.5 * sign * eps_shear
                strains.append((f"shear_{label}_{'p' if sign > 0 else 'm'}", strain, "shear"))

    return strains


def deterministic_random_displace(atoms: Atoms, amplitude: float, seed: int) -> Atoms:
    result = atoms.copy()
    rng = np.random.default_rng(seed)
    disp = rng.normal(size=(len(result), 3))
    norms = np.linalg.norm(disp, axis=1)
    norms[norms == 0.0] = 1.0
    disp = disp / norms[:, None]
    mags = rng.random(len(result)) * amplitude
    result.positions = result.positions + disp * mags[:, None]
    return result


def write_case(
    atoms: Atoms,
    run_dir: Path,
    info: dict,
    template_dir: Path | None,
    copy_template_all: bool,
) -> None:
    ensure_dir(run_dir)
    write(run_dir / "POSCAR", atoms, format="vasp", direct=True, vasp5=True, sort=False)
    (run_dir / "case_info.json").write_text(json.dumps(info, indent=2) + "\n", encoding="utf-8")
    copy_vasp_template(template_dir, run_dir, copy_all=copy_template_all)


def phonopy_dim_args(dim: tuple[int, int, int]) -> list[str]:
    return ["--dim", str(dim[0]), str(dim[1]), str(dim[2])]


def run_phonopy(
    work_dir: Path,
    poscar_atoms: Atoms,
    command: list[str],
    phonopy_cmd: str,
) -> list[Path]:
    if work_dir.exists():
        shutil.rmtree(work_dir)
    ensure_dir(work_dir)
    write(work_dir / "POSCAR", poscar_atoms, format="vasp", direct=True, vasp5=True, sort=False)

    full_command = [phonopy_cmd, *command]
    print("Running:", " ".join(full_command), "  (cwd:", work_dir, ")")
    subprocess.run(full_command, cwd=str(work_dir), check=True)
    poscars = sorted(work_dir.glob("POSCAR-*"))
    if not poscars:
        raise RuntimeError(f"No POSCAR-* generated by phonopy in {work_dir}.")
    return poscars


def move_phonopy_poscars(
    poscars: list[Path],
    vol_dir: Path,
    prefix: str,
    dataset: str,
    kind: str,
    family: str,
    volume_fraction: float,
    source_poscar: Path,
    template_dir: Path | None,
    copy_template_all: bool,
    info: str,
) -> list[PhonopyRecord]:
    records = []
    for poscar in poscars:
        tag = poscar.name.split("-", 1)[1]
        run_dir = ensure_dir(vol_dir / f"{prefix}_{tag}")
        shutil.move(str(poscar), str(run_dir / "POSCAR"))
        copy_vasp_template(template_dir, run_dir, copy_all=copy_template_all)
        case_info = {
            "dataset": dataset,
            "kind": kind,
            "family": family,
            "volume_fraction": volume_fraction,
            "source_poscar": str(source_poscar),
            "phonopy_poscar_tag": tag,
            "info": info,
        }
        (run_dir / "case_info.json").write_text(
            json.dumps(case_info, indent=2) + "\n",
            encoding="utf-8",
        )
        records.append(
            PhonopyRecord(
                run_dir=run_dir,
                dataset=dataset,
                kind=kind,
                family=family,
                volume_fraction=volume_fraction,
                source_poscar=source_poscar,
                info=info,
            )
        )
    return records


def keep_phonopy_metadata(work_dir: Path, metadata_dir: Path) -> None:
    ensure_dir(metadata_dir)
    for item in sorted(work_dir.iterdir()):
        if item.name == "POSCAR" or item.name.startswith("POSCAR-"):
            continue
        target = metadata_dir / item.name
        if item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True)
        elif item.is_file():
            shutil.copy2(item, target)


def write_runlist(records: list[PhonopyRecord], runlist: Path) -> None:
    ensure_dir(runlist.parent)
    base = runlist.parent.resolve()
    lines = []
    for record in records:
        try:
            lines.append(str(record.run_dir.resolve().relative_to(base)))
        except ValueError:
            lines.append(str(record.run_dir.resolve()))
    runlist.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def write_index(records: list[PhonopyRecord], index_path: Path) -> None:
    ensure_dir(index_path.parent)
    with index_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=(
                "run_dir",
                "dataset",
                "kind",
                "family",
                "volume_fraction",
                "source_poscar",
                "info",
            ),
        )
        writer.writeheader()
        for record in records:
            writer.writerow(
                {
                    "run_dir": str(record.run_dir.resolve()),
                    "dataset": record.dataset,
                    "kind": record.kind,
                    "family": record.family,
                    "volume_fraction": record.volume_fraction,
                    "source_poscar": str(record.source_poscar.resolve()),
                    "info": record.info,
                }
            )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="vasp-phonopy-neareq",
        description="Prepare phonopy and MLIP near-equilibrium VASP datasets.",
    )
    parser.add_argument(
        "--poscar",
        type=Path,
        default=None,
        help="Reference POSCAR. Defaults to VASP_TEMPLATE/POSCAR, then ./POSCAR.",
    )
    parser.add_argument("--output-root", "--out", dest="output_root", type=Path, required=True)
    parser.add_argument("--vasp-template", type=Path, default=None)
    parser.add_argument("--copy-template-all", action="store_true")
    parser.add_argument("--runlist", type=Path, default=None)
    parser.add_argument("--index", type=Path, default=None)
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--mode", choices=("phonopy", "mlip", "both"), default="both")
    parser.add_argument("--phonopy-cmd", default="phonopy")
    parser.add_argument("--dim", nargs=3, type=int, default=[1, 1, 1])
    parser.add_argument(
        "--vol-fracs",
        nargs="+",
        type=float,
        default=[0.985, 0.99, 0.995, 1.00, 1.005, 1.01, 1.015],
    )

    parser.add_argument(
        "--phonopy-displacements",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Run phonopy -d for the full finite-displacement phonopy set.",
    )
    parser.add_argument("--rd", type=int, default=8, help="Phonopy random-displacement cells per volume.")
    parser.add_argument("--amplitude", type=float, default=0.015)
    parser.add_argument("--tolerance", type=float, default=0.01)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--eps-hydro", nargs="+", type=float, default=[0.005, 0.01])
    parser.add_argument("--eps-uni", type=float, default=0.005)
    parser.add_argument("--eps-shear", type=float, default=0.003)
    parser.add_argument("--no-uniaxial", action="store_true")
    parser.add_argument("--no-shear", action="store_true")
    parser.add_argument("--rd-on-strain", type=int, default=2)
    parser.add_argument("--rd-strain-amplitude", type=float, default=0.01)
    return parser


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)

    output_root = ensure_dir(args.output_root.resolve())
    template_dir = args.vasp_template.resolve() if args.vasp_template else None
    poscar = resolve_input_poscar(args.poscar, template_dir)
    dim = tuple(args.dim)
    ref = read(poscar)
    validate_vasp_template(template_dir, atoms=ref, require_poscar=args.poscar is None)
    strain_set = make_strain_set(
        hydro_list=args.eps_hydro,
        eps_uni=args.eps_uni,
        eps_shear=args.eps_shear,
        include_uniaxial=not args.no_uniaxial,
        include_shear=not args.no_shear,
    )

    records: list[PhonopyRecord] = []
    for vol_fraction in args.vol_fracs:
        vol_dir = ensure_dir(output_root / f"V{vol_fraction:.3f}")
        atoms = ref.copy()
        scale = vol_fraction ** (1.0 / 3.0)
        atoms.set_cell(ref.cell * scale, scale_atoms=True)
        write(vol_dir / "POSCAR", atoms, format="vasp", direct=True, vasp5=True, sort=False)

        if args.mode in ("phonopy", "both") and args.phonopy_displacements:
            work_dir = vol_dir / "_phonopy_displacements_work"
            poscars = run_phonopy(
                work_dir=work_dir,
                poscar_atoms=atoms,
                command=["-d", *phonopy_dim_args(dim)],
                phonopy_cmd=args.phonopy_cmd,
            )
            records.extend(
                move_phonopy_poscars(
                    poscars=poscars,
                    vol_dir=vol_dir,
                    prefix="phonopy",
                    dataset="phonopy",
                    kind="finite_displacement",
                    family="phonopy",
                    volume_fraction=vol_fraction,
                    source_poscar=poscar,
                    template_dir=template_dir,
                    copy_template_all=args.copy_template_all,
                    info="phonopy -d",
                )
            )
            keep_phonopy_metadata(work_dir, vol_dir / "phonopy_displacement_metadata")

        if args.mode in ("mlip", "both"):
            if args.rd > 0:
                work_dir = vol_dir / "_phonopy_random_work"
                poscars = run_phonopy(
                    work_dir=work_dir,
                    poscar_atoms=atoms,
                    command=[
                        "--vasp",
                        "-c",
                        "POSCAR",
                        *phonopy_dim_args(dim),
                        "--rd",
                        str(args.rd),
                        "--amplitude",
                        str(args.amplitude),
                        "--random-seed",
                        str(args.seed),
                        "--tolerance",
                        str(args.tolerance),
                    ],
                    phonopy_cmd=args.phonopy_cmd,
                )
                records.extend(
                    move_phonopy_poscars(
                        poscars=poscars,
                        vol_dir=vol_dir,
                        prefix="rd",
                        dataset="mlip_neareq",
                        kind="phonopy_random_displacement",
                        family="rd",
                        volume_fraction=vol_fraction,
                        source_poscar=poscar,
                        template_dir=template_dir,
                        copy_template_all=args.copy_template_all,
                        info=f"phonopy --rd amplitude={args.amplitude}",
                    )
                )
                keep_phonopy_metadata(work_dir, vol_dir / "phonopy_random_metadata")

            for index, (name, strain, family) in enumerate(strain_set, start=1):
                strained = apply_strain(atoms, strain)
                run_dir = vol_dir / f"strain_{index:03d}_{name}"
                info = {
                    "dataset": "mlip_neareq",
                    "kind": "strain",
                    "family": family,
                    "volume_fraction": vol_fraction,
                    "source_poscar": str(poscar),
                    "strain_name": name,
                    "strain_matrix": strain.tolist(),
                }
                write_case(strained, run_dir, info, template_dir, args.copy_template_all)
                records.append(
                    PhonopyRecord(
                        run_dir=run_dir,
                        dataset="mlip_neareq",
                        kind="strain",
                        family=family,
                        volume_fraction=vol_fraction,
                        source_poscar=poscar,
                        info=name,
                    )
                )

                for copy_index in range(1, args.rd_on_strain + 1):
                    strained_rd = deterministic_random_displace(
                        strained,
                        amplitude=args.rd_strain_amplitude,
                        seed=args.seed + 100000 * index + copy_index,
                    )
                    rd_dir = vol_dir / f"strainrd_{index:03d}_{name}_{copy_index:03d}"
                    rd_info = {
                        **info,
                        "kind": "strain_random_displacement",
                        "rd_amplitude": args.rd_strain_amplitude,
                        "rd_seed": args.seed + 100000 * index + copy_index,
                    }
                    write_case(strained_rd, rd_dir, rd_info, template_dir, args.copy_template_all)
                    records.append(
                        PhonopyRecord(
                            run_dir=rd_dir,
                            dataset="mlip_neareq",
                            kind="strain_random_displacement",
                            family=family,
                            volume_fraction=vol_fraction,
                            source_poscar=poscar,
                            info=f"{name};rd_amp={args.rd_strain_amplitude}",
                        )
                    )

    runlist = args.runlist.resolve() if args.runlist else output_root / "runlist.txt"
    index_path = args.index.resolve() if args.index else output_root / "candidate_index.csv"
    manifest = args.manifest.resolve() if args.manifest else output_root / "manifest.csv"
    write_runlist(records, runlist)
    write_index(records, index_path)
    write_index(records, manifest)

    phonopy_records = [record for record in records if record.dataset == "phonopy"]
    mlip_records = [record for record in records if record.dataset == "mlip_neareq"]
    phonopy_runlist = output_root / "runlist_phonopy.txt"
    mlip_runlist = output_root / "runlist_mlip_neareq.txt"
    if phonopy_records:
        write_runlist(phonopy_records, phonopy_runlist)
    if mlip_records:
        write_runlist(mlip_records, mlip_runlist)

    counts: dict[tuple[str, str], int] = {}
    for record in records:
        key = (record.dataset, record.kind)
        counts[key] = counts.get(key, 0) + 1

    print("")
    print(f"Source POSCAR : {poscar}")
    print(f"Structure     : {summarize_atoms(ref)}")
    print(f"Species order : {', '.join(species_order_from_atoms(ref))}")
    print(f"Output root   : {output_root}")
    print(f"Mode          : {args.mode}")
    print(f"Volumes       : {args.vol_fracs}")
    print(f"Total runs    : {len(records)}")
    for (dataset, kind), count in sorted(counts.items()):
        print(f"  {dataset:14s} {kind:30s} {count:5d}")
    print(f"Runlist       : {runlist}")
    if phonopy_records:
        print(f"Phonopy list  : {phonopy_runlist}")
    if mlip_records:
        print(f"MLIP list     : {mlip_runlist}")
    print(f"Index         : {index_path}")
    print(f"Manifest      : {manifest}")
