from __future__ import annotations

import argparse
import textwrap
from pathlib import Path
from typing import Any


def _require_yaml() -> Any:
    try:
        import yaml  # type: ignore[import-not-found]
    except ImportError as exc:
        raise SystemExit("PyYAML is required to read band.yaml. Try: python -m pip install pyyaml") from exc
    return yaml


def _require_pyplot() -> Any:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt  # type: ignore[import-not-found]
    except ImportError as exc:
        raise SystemExit("matplotlib is required to plot band.yaml. Try: python -m pip install matplotlib") from exc
    return plt


def load_band_yaml(path: Path) -> tuple[list[float], list[list[float]], list[int] | None, list[Any] | None]:
    if not path.exists():
        raise FileNotFoundError(f"Could not find band YAML: {path}")

    yaml = _require_yaml()
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    phonons = data.get("phonon", [])
    if not phonons:
        raise ValueError(f"No 'phonon' entries found in {path}")

    distances: list[float] = []
    frequencies: list[list[float]] = []
    for point in phonons:
        distances.append(float(point["distance"]))
        bands = point.get("band", [])
        frequencies.append([float(band["frequency"]) for band in bands])

    if not frequencies or not frequencies[0]:
        raise ValueError(f"No band frequencies found in {path}")

    n_branch = len(frequencies[0])
    for row in frequencies:
        if len(row) != n_branch:
            raise ValueError(f"Inconsistent number of phonon branches in {path}")

    segment_nqpoint = data.get("segment_nqpoint")
    if segment_nqpoint is not None:
        segment_nqpoint = [int(value) for value in segment_nqpoint]

    labels = data.get("labels")
    return distances, frequencies, segment_nqpoint, labels


def segment_indices(segment_nqpoint: list[int] | None, n_total: int) -> list[tuple[int, int]]:
    if not segment_nqpoint:
        return [(0, n_total)]

    segments: list[tuple[int, int]] = []
    start = 0
    for n_points in segment_nqpoint:
        end = min(start + int(n_points), n_total)
        if end > start:
            segments.append((start, end))
        start = end

    if not segments or segments[-1][1] < n_total:
        segments.append((segments[-1][1] if segments else 0, n_total))
    return segments


def _format_label(label: Any) -> str:
    text = str(label)
    if text in {"G", "Gamma", "GAMMA", "\\Gamma"}:
        return r"$\Gamma$"
    return text


def _tick_labels(
    distances: list[float],
    segments: list[tuple[int, int]],
    labels: list[Any] | None,
) -> tuple[list[float], list[str] | None]:
    ticks = [distances[start] for start, _ in segments]
    ticks.append(distances[segments[-1][1] - 1])
    if not labels:
        return ticks, None

    tick_labels: list[str] = []
    first = labels[0][0] if isinstance(labels[0], list) else labels[0]
    tick_labels.append(_format_label(first))
    for index, (_, end) in enumerate(segments):
        if index < len(labels):
            label = labels[index][1] if isinstance(labels[index], list) and len(labels[index]) > 1 else labels[index]
        else:
            label = ""
        tick_labels.append(_format_label(label))

    return ticks, tick_labels


def plot_band_structure(
    band_yaml: Path,
    outpng: Path,
    title: str = "Phonon band structure",
    ylabel: str = "Frequency (THz)",
) -> None:
    distances, frequencies, segment_nqpoint, labels = load_band_yaml(band_yaml)
    segments = segment_indices(segment_nqpoint, len(distances))
    n_branch = len(frequencies[0])

    plt = _require_pyplot()
    fig, ax = plt.subplots(figsize=(7.2, 5.2))

    for start, end in segments:
        x = distances[start:end]
        for branch in range(n_branch):
            y = [row[branch] for row in frequencies[start:end]]
            ax.plot(x, y, color="black", linewidth=1.0)

    ticks, tick_labels = _tick_labels(distances, segments, labels)
    for tick in ticks:
        ax.axvline(x=tick, color="0.65", linewidth=0.6)
    ax.axhline(y=0.0, color="0.55", linewidth=0.8, linestyle="--")
    ax.set_xlim(min(distances), max(distances))
    ax.set_xlabel("Wave vector")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    if tick_labels:
        ax.set_xticks(ticks, tick_labels)
    else:
        ax.set_xticks(ticks)
    fig.tight_layout()
    fig.savefig(outpng, dpi=300)
    plt.close(fig)


def standalone_script_text() -> str:
    return textwrap.dedent(
        r'''
        #!/usr/bin/env python3
        """Plot phonopy band.yaml to a PNG.

        Generated by atomi vasp-phonopy-post so the Slurm job can plot band.yaml
        without importing the atomi package from the active phonopy environment.
        """

        from __future__ import annotations

        import argparse
        from pathlib import Path


        def load_band_yaml(path):
            try:
                import yaml
            except ImportError as exc:
                raise SystemExit("PyYAML is required to read band.yaml. Try: python -m pip install pyyaml") from exc
            if not path.exists():
                raise FileNotFoundError(f"Could not find band YAML: {path}")
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            phonons = data.get("phonon", [])
            if not phonons:
                raise ValueError(f"No 'phonon' entries found in {path}")
            distances = []
            frequencies = []
            for point in phonons:
                distances.append(float(point["distance"]))
                frequencies.append([float(band["frequency"]) for band in point.get("band", [])])
            if not frequencies or not frequencies[0]:
                raise ValueError(f"No band frequencies found in {path}")
            n_branch = len(frequencies[0])
            if any(len(row) != n_branch for row in frequencies):
                raise ValueError(f"Inconsistent number of phonon branches in {path}")
            segment_nqpoint = data.get("segment_nqpoint")
            if segment_nqpoint is not None:
                segment_nqpoint = [int(value) for value in segment_nqpoint]
            return distances, frequencies, segment_nqpoint, data.get("labels")


        def segment_indices(segment_nqpoint, n_total):
            if not segment_nqpoint:
                return [(0, n_total)]
            segments = []
            start = 0
            for n_points in segment_nqpoint:
                end = min(start + int(n_points), n_total)
                if end > start:
                    segments.append((start, end))
                start = end
            if not segments or segments[-1][1] < n_total:
                segments.append((segments[-1][1] if segments else 0, n_total))
            return segments


        def format_label(label):
            text = str(label)
            if text in {"G", "Gamma", "GAMMA", "\\Gamma"}:
                return r"$\Gamma$"
            return text


        def tick_labels(distances, segments, labels):
            ticks = [distances[start] for start, _ in segments]
            ticks.append(distances[segments[-1][1] - 1])
            if not labels:
                return ticks, None
            out = []
            first = labels[0][0] if isinstance(labels[0], list) else labels[0]
            out.append(format_label(first))
            for index, (_, end) in enumerate(segments):
                if index < len(labels):
                    label = (
                        labels[index][1]
                        if isinstance(labels[index], list) and len(labels[index]) > 1
                        else labels[index]
                    )
                else:
                    label = ""
                out.append(format_label(label))
            return ticks, out


        def plot_band_structure(band_yaml, outpng, title, ylabel):
            try:
                import matplotlib
                matplotlib.use("Agg")
                import matplotlib.pyplot as plt
            except ImportError as exc:
                raise SystemExit(
                    "matplotlib is required to plot band.yaml. Try: python -m pip install matplotlib"
                ) from exc

            distances, frequencies, segment_nqpoint, labels = load_band_yaml(band_yaml)
            segments = segment_indices(segment_nqpoint, len(distances))
            n_branch = len(frequencies[0])
            fig, ax = plt.subplots(figsize=(7.2, 5.2))
            for start, end in segments:
                x = distances[start:end]
                for branch in range(n_branch):
                    ax.plot(x, [row[branch] for row in frequencies[start:end]], color="black", linewidth=1.0)
            ticks, names = tick_labels(distances, segments, labels)
            for tick in ticks:
                ax.axvline(x=tick, color="0.65", linewidth=0.6)
            ax.axhline(y=0.0, color="0.55", linewidth=0.8, linestyle="--")
            ax.set_xlim(min(distances), max(distances))
            ax.set_xlabel("Wave vector")
            ax.set_ylabel(ylabel)
            ax.set_title(title)
            if names:
                ax.set_xticks(ticks, names)
            else:
                ax.set_xticks(ticks)
            fig.tight_layout()
            fig.savefig(outpng, dpi=300)
            plt.close(fig)
            print(f"Saved: {outpng}")


        def main(argv=None):
            parser = argparse.ArgumentParser(description="Plot phonopy band.yaml to a PNG.")
            parser.add_argument("--band-yaml", type=Path, default=Path("band.yaml"))
            parser.add_argument("--outpng", type=Path, default=Path("phonon_band.png"))
            parser.add_argument("--title", default="Phonon band structure")
            parser.add_argument("--ylabel", default="Frequency (THz)")
            args = parser.parse_args(argv)
            plot_band_structure(args.band_yaml, args.outpng, args.title, args.ylabel)


        if __name__ == "__main__":
            main()
        '''
    ).lstrip()


def write_standalone_script(path: Path) -> None:
    path.write_text(standalone_script_text(), encoding="utf-8")
    path.chmod(0o755)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Plot phonopy band.yaml to a PNG.")
    parser.add_argument("--band-yaml", type=Path, default=Path("band.yaml"))
    parser.add_argument("--outpng", type=Path, default=Path("phonon_band.png"))
    parser.add_argument("--title", default="Phonon band structure")
    parser.add_argument("--ylabel", default="Frequency (THz)")
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    plot_band_structure(args.band_yaml, args.outpng, args.title, args.ylabel)
    print(f"Saved: {args.outpng}")


if __name__ == "__main__":
    main()
