"""OpenMolcas D2h-subgroup symmetry helpers.

OpenMolcas supports D2h and its Abelian subgroups through sign-change
generators.  This module keeps that convention explicit so MOLCAS input
preparation can choose between ``GROUP=FULL``, an explicit generator list, or
``GROUP=NOSYM`` with a documented reason.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
from pathlib import Path
from typing import Any, Iterable, Sequence

from atomi.local_structure import read_atoms


SCHEMA = "atomi.openmolcas_symmetry_plan.v1"

OPERATION_MASKS: dict[str, int] = {
    "E": 0,
    "X": 1,
    "Y": 2,
    "Z": 4,
    "XY": 3,
    "XZ": 5,
    "YZ": 6,
    "XYZ": 7,
}
MASK_OPERATIONS = {value: key for key, value in OPERATION_MASKS.items()}
OPERATION_ORDER = ("E", "X", "Y", "Z", "XY", "XZ", "YZ", "XYZ")
GENERATOR_ORDER = ("X", "Y", "Z", "XY", "XZ", "YZ", "XYZ")

D2H_ORDER = ("Ag", "B3u", "B2u", "B1g", "B1u", "B2g", "B3g", "Au")
D2H_PRODUCT_TABLE = {
    "Ag": {"Ag": "Ag", "B3u": "B3u", "B2u": "B2u", "B1g": "B1g", "B1u": "B1u", "B2g": "B2g", "B3g": "B3g", "Au": "Au"},
    "B3u": {"Ag": "B3u", "B3u": "Ag", "B2u": "B1g", "B1g": "B2u", "B1u": "B2g", "B2g": "B1u", "B3g": "Au", "Au": "B3g"},
    "B2u": {"Ag": "B2u", "B3u": "B1g", "B2u": "Ag", "B1g": "B3u", "B1u": "B3g", "B2g": "Au", "B3g": "B1u", "Au": "B2g"},
    "B1g": {"Ag": "B1g", "B3u": "B2u", "B2u": "B3u", "B1g": "Ag", "B1u": "Au", "B2g": "B3g", "B3g": "B2g", "Au": "B1u"},
    "B1u": {"Ag": "B1u", "B3u": "B2g", "B2u": "B3g", "B1g": "Au", "B1u": "Ag", "B2g": "B3u", "B3g": "B2u", "Au": "B1g"},
    "B2g": {"Ag": "B2g", "B3u": "B1u", "B2u": "Au", "B1g": "B3g", "B1u": "B3u", "B2g": "Ag", "B3g": "B1g", "Au": "B2u"},
    "B3g": {"Ag": "B3g", "B3u": "Au", "B2u": "B1u", "B1g": "B2g", "B1u": "B2u", "B2g": "B1g", "B3g": "Ag", "Au": "B3u"},
    "Au": {"Ag": "Au", "B3u": "B3g", "B2u": "B2g", "B1g": "B1u", "B1u": "B1g", "B2g": "B2u", "B3g": "B3u", "Au": "Ag"},
}
D2H_DIPOLE_IRREPS = {"x": "B3u", "y": "B2u", "z": "B1u"}

OPERATION_DESCRIPTIONS = {
    "E": "identity",
    "X": "reflection in yz plane; x -> -x",
    "Y": "reflection in xz plane; y -> -y",
    "Z": "reflection in xy plane; z -> -z",
    "XY": "twofold rotation about z; x,y -> -x,-y",
    "XZ": "twofold rotation about y; x,z -> -x,-z",
    "YZ": "twofold rotation about x; y,z -> -y,-z",
    "XYZ": "inversion through origin",
}

STANDARD_IRREP_LABELS = {
    "C1": ("A",),
    "Cs": ("A'", 'A"'),
    "C2": ("A", "B"),
    "Ci": ("Ag", "Au"),
    "C2v": ("A1", "B1", "B2", "A2"),
    "C2h": ("Ag", "Bg", "Au", "Bu"),
    "D2": ("A", "B1", "B2", "B3"),
    "D2h": D2H_ORDER,
}


def _mask(label: str) -> int:
    key = label.strip().upper()
    if key not in OPERATION_MASKS:
        raise ValueError(f"Unknown Molcas symmetry operation {label!r}")
    return OPERATION_MASKS[key]


def operation_product(left: str, right: str) -> str:
    """Return product of two Molcas sign-change operations."""

    return MASK_OPERATIONS[_mask(left) ^ _mask(right)]


def closure(generators: Iterable[str]) -> tuple[str, ...]:
    """Return the operation closure generated by Molcas sign-change operators."""

    masks = {0}
    for generator in generators:
        masks.add(_mask(generator))
    changed = True
    while changed:
        changed = False
        for a, b in itertools.product(tuple(masks), repeat=2):
            product = a ^ b
            if product not in masks:
                masks.add(product)
                changed = True
    return tuple(label for label in OPERATION_ORDER if OPERATION_MASKS[label] in masks)


def classify_operations(operations: Sequence[str]) -> str:
    """Classify a closed Molcas sign-change operation set."""

    masks = {_mask(op) for op in operations}
    order = len(masks)
    if order == 1:
        return "C1"
    if order == 2:
        only = next(mask for mask in masks if mask)
        if only in (1, 2, 4):
            return "Cs"
        if only in (3, 5, 6):
            return "C2"
        if only == 7:
            return "Ci"
    if order == 4:
        if 7 in masks:
            return "C2h"
        if masks.issubset({0, 3, 5, 6}):
            return "D2"
        return "C2v"
    if order == 8:
        return "D2h"
    raise ValueError(f"Operation set is not a Molcas D2h subgroup: {operations!r}")


def generator_set_for_operations(operations: Sequence[str]) -> tuple[str, ...]:
    """Return a compact explicit generator list for a closed operation set."""

    target = set(operations)
    if target == {"E"}:
        return ()
    for size in (1, 2, 3):
        for combo in itertools.combinations(GENERATOR_ORDER, size):
            if set(closure(combo)) == target:
                return combo
    raise ValueError(f"Could not find Molcas generators for operations {operations!r}")


def molcas_group_keyword(generators: Sequence[str]) -> str:
    if not generators:
        return "NOSYM"
    return " ".join(generators)


def _operation_signs(label: str) -> tuple[int, int, int]:
    mask = _mask(label)
    return (-1 if mask & 1 else 1, -1 if mask & 2 else 1, -1 if mask & 4 else 1)


def _center_coordinates(
    coords: Sequence[Sequence[float]],
    symbols: Sequence[str],
    *,
    center: str,
    center_index: int | None,
) -> tuple[list[list[float]], list[float]]:
    if not coords:
        return [], [0.0, 0.0, 0.0]
    if center == "origin":
        origin = [0.0, 0.0, 0.0]
    elif center == "centroid":
        origin = [sum(row[i] for row in coords) / len(coords) for i in range(3)]
    elif center == "first-atom":
        origin = [float(v) for v in coords[0]]
    elif center == "atom":
        if center_index is None:
            raise ValueError("center='atom' requires center_index")
        if center_index < 1 or center_index > len(coords):
            raise ValueError(f"center_index must be in 1..{len(coords)}, got {center_index}")
        origin = [float(v) for v in coords[center_index - 1]]
    elif center == "heavy-atom":
        from atomi.structure.elements import atomic_number

        heavy = max(range(len(symbols)), key=lambda idx: atomic_number(symbols[idx]))
        origin = [float(v) for v in coords[heavy]]
    else:
        raise ValueError(f"Unknown center mode {center!r}")
    shifted = [[float(row[i]) - origin[i] for i in range(3)] for row in coords]
    return shifted, origin


def operation_is_valid(
    symbols: Sequence[str],
    coords: Sequence[Sequence[float]],
    operation: str,
    *,
    tolerance: float = 0.01,
) -> bool:
    """Return whether a sign-change operation maps atoms onto same-element atoms."""

    signs = _operation_signs(operation)
    transformed = [[signs[i] * float(row[i]) for i in range(3)] for row in coords]
    unmatched = set(range(len(coords)))
    for symbol, target in zip(symbols, transformed):
        found = None
        for idx in unmatched:
            if symbols[idx] != symbol:
                continue
            distance = math.sqrt(sum((float(coords[idx][dim]) - target[dim]) ** 2 for dim in range(3)))
            if distance <= tolerance:
                found = idx
                break
        if found is None:
            return False
        unmatched.remove(found)
    return True


def detect_molcas_sign_flip_symmetry(
    symbols: Sequence[str],
    coords: Sequence[Sequence[float]],
    *,
    tolerance: float = 0.01,
    center: str = "centroid",
    center_index: int | None = None,
) -> dict[str, Any]:
    """Detect the highest current-axis Molcas D2h-subgroup symmetry."""

    shifted, origin = _center_coordinates(coords, symbols, center=center, center_index=center_index)
    valid = {"E"}
    for operation in GENERATOR_ORDER:
        if operation_is_valid(symbols, shifted, operation, tolerance=tolerance):
            valid.add(operation)
    operations = ("E",)
    for size in (1, 2, 3):
        for combo in itertools.combinations(GENERATOR_ORDER, size):
            candidate = closure(combo)
            if all(op in valid for op in candidate) and len(candidate) > len(operations):
                operations = candidate
    generators = generator_set_for_operations(operations)
    group = classify_operations(operations)
    warnings: list[str] = []
    if group == "D2h":
        warnings.append("If the real local point group is Oh/Td/etc., OpenMolcas still uses only a D2h subgroup; degenerate components may split across irreps.")
    if center != "origin":
        warnings.append("Detection was done after recentering coordinates; use Molcas MOVE/GROUP=FULL or inspect findsym.std before production.")
    if generators:
        warnings.append("Irrep ordering and labels depend on the chosen generator order; parse GATEWAY/SCF output before assigning active-orbital rotations.")
    return {
        "schema": SCHEMA,
        "group": group,
        "operations": list(operations),
        "generators": list(generators),
        "molcas_group_keyword": molcas_group_keyword(generators),
        "standard_irrep_labels": list(STANDARD_IRREP_LABELS[group]),
        "operation_descriptions": {op: OPERATION_DESCRIPTIONS[op] for op in operations},
        "tolerance_A": tolerance,
        "center_mode": center,
        "center_index_1based": center_index,
        "origin_A": origin,
        "warnings": warnings,
    }


def read_structure_for_symmetry(path: Path, *, backend: str = "ase") -> tuple[list[str], list[list[float]]]:
    atoms = read_atoms(path, backend=backend)
    symbols = [str(symbol) for symbol in atoms.get_chemical_symbols()]
    coords = [[float(v) for v in row] for row in atoms.get_positions()]
    return symbols, coords


def detect_structure_symmetry(
    path: Path,
    *,
    backend: str = "ase",
    tolerance: float = 0.01,
    center: str = "centroid",
    center_index: int | None = None,
) -> dict[str, Any]:
    symbols, coords = read_structure_for_symmetry(path, backend=backend)
    payload = detect_molcas_sign_flip_symmetry(
        symbols,
        coords,
        tolerance=tolerance,
        center=center,
        center_index=center_index,
    )
    payload["structure"] = str(path)
    payload["n_atoms"] = len(symbols)
    payload["elements"] = sorted(set(symbols))
    return payload


def d2h_product_counts(core_counts: dict[str, int], acceptor_counts: dict[str, int]) -> dict[str, int]:
    """Return D2h final-irrep counts for one-electron core -> acceptor promotions."""

    products = {irrep: 0 for irrep in D2H_ORDER}
    for core_irrep, core_count in core_counts.items():
        if core_irrep not in D2H_ORDER:
            raise ValueError(f"Unknown D2h irrep {core_irrep!r}")
        for acc_irrep, acc_count in acceptor_counts.items():
            if acc_irrep not in D2H_ORDER:
                raise ValueError(f"Unknown D2h irrep {acc_irrep!r}")
            products[D2H_PRODUCT_TABLE[core_irrep][acc_irrep]] += int(core_count) * int(acc_count)
    return {irrep: count for irrep, count in products.items() if count}


def d2h_product(left: str, right: str) -> str:
    """Return the D2h direct-product irrep in OpenMolcas ordering."""

    if left not in D2H_ORDER:
        raise ValueError(f"Unknown D2h irrep {left!r}")
    if right not in D2H_ORDER:
        raise ValueError(f"Unknown D2h irrep {right!r}")
    return D2H_PRODUCT_TABLE[left][right]


def d2h_dipole_allowed_final_irreps(
    initial_irrep: str,
    *,
    dipole_irreps: dict[str, str] | None = None,
) -> dict[str, str]:
    """Return electric-dipole allowed final irreps for a D2h initial state.

    The default uses the conventional OpenMolcas D2h axis assignment:
    x -> B3u, y -> B2u, z -> B1u.  The return value preserves the polarization
    labels because XANES inputs often need to retain x/y/z provenance even when
    two axes collapse under a lower subgroup.
    """

    axes = dipole_irreps or D2H_DIPOLE_IRREPS
    if initial_irrep not in D2H_ORDER:
        raise ValueError(f"Unknown D2h irrep {initial_irrep!r}")
    return {axis: d2h_product(initial_irrep, irrep) for axis, irrep in axes.items()}


def _write_json(payload: dict[str, Any], path: Path | None) -> None:
    text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    else:
        print(text, end="")


def _detect(args: argparse.Namespace) -> int:
    payload = detect_structure_symmetry(
        args.structure,
        backend=args.backend,
        tolerance=args.tolerance,
        center=args.center,
        center_index=args.center_index,
    )
    _write_json(payload, args.write_json)
    return 0


def _generators(args: argparse.Namespace) -> int:
    operations = closure(args.generators)
    group = classify_operations(operations)
    payload = {
        "schema": SCHEMA,
        "input_generators": args.generators,
        "group": group,
        "operations": list(operations),
        "generators": list(generator_set_for_operations(operations)),
        "molcas_group_keyword": molcas_group_keyword(generator_set_for_operations(operations)),
        "standard_irrep_labels": list(STANDARD_IRREP_LABELS[group]),
        "operation_descriptions": {op: OPERATION_DESCRIPTIONS[op] for op in operations},
    }
    _write_json(payload, args.write_json)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Detect and document OpenMolcas D2h-subgroup symmetry choices.")
    sub = parser.add_subparsers(dest="command", required=True)

    detect = sub.add_parser("detect", help="Detect sign-change symmetry for an XYZ/POSCAR/CIF-like structure.")
    detect.add_argument("--structure", type=Path, required=True)
    detect.add_argument("--backend", choices=("ase", "pymatgen"), default="ase")
    detect.add_argument("--tolerance", type=float, default=0.01)
    detect.add_argument("--center", choices=("origin", "centroid", "first-atom", "atom", "heavy-atom"), default="centroid")
    detect.add_argument("--center-index", type=int, default=None)
    detect.add_argument("--write-json", type=Path)
    detect.set_defaults(func=_detect)

    gens = sub.add_parser("generators", help="Classify an explicit Molcas generator list, e.g. X Y Z.")
    gens.add_argument("generators", nargs="*")
    gens.add_argument("--write-json", type=Path)
    gens.set_defaults(func=_generators)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
